services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/src/data
      - ./app/app:/src/app/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - HF_HOME=/root/.cache/huggingface
